### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by dseidl** [paulgibbs/behat-wordpress-extension#109]
You cant install your package if you follow the docs on [https://wordhat.info/installation/index.html](https://wordhat.info/installation/index.html)

## Current behavior
![screen shot 2017-07-11 at 11 10 56](https://user-images.githubusercontent.com/8925933/28061211-111369e4-662a-11e7-8de3-ae6fd954250a.png)

## Possible solution
Change docs to install without dev-master
Your added dependencie https://github.com/Roave/SecurityAdvisories does not allow that.

## Steps to reproduce (for bugs)
follow your docs.

**Comment by paulgibbs** [comment]
Sure, for now, use the 0.7 version.

The docs say dev-master because a few months ago (when they were written), the basic infrastructure was changing pretty dynamically.

I'll this fixed today (both the docs and the dependancy resolution).

**Comment by stephenharris** [comment]
Shouldn't we have the `roave/security-advisories` as a dev-requirement rather than a requirement? It feels like we're imposing dependencies that are not strictly required for WordHat to function. Putting it as a dev requirement means we can ensure there are no security vulnerabilities in our application, but it doesn't add any further requirements on downstream clients.

**Comment by paulgibbs** [comment]
Docs updated to remove `dev-master` specificity (defaults to latest stable; currently 0.7).

**Comment by paulgibbs** [comment]
Removing `dev-master` from this line fixes the dependancy resolution problem.

**Comment by paulgibbs** [comment]
> Shouldn't we have the roave/security-advisories as a dev-requirement rather than a requirement?

I don't think so. The idea of putting it as a requirement is that if we depend on something (for a given release) that's later flagged as having a security problem, our users will be blocked from that using that version of WordHat, forcing them to upgrade to a newer version.

**Comment by paulgibbs** [comment]
As always, if you strongly think I'm going mad, feel free to change it. I trust your decisions.

**Comment by stephenharris** [comment]
Is it our call to make? Presumably if the client cares they will have the security vulnerabilities package installed themselves.

An end user may, for whatever reason, be happy to use a vulnerable version because of the environment its used in.

My view is that our responsibility is to ensure we don't ship a release with known vulnerabilities. Its the client responsibility to decide if they are going to use a version with a known vulnerability. 

(Also this seems to stop us using branches instead of tagged releases...?)

**Comment by paulgibbs** [comment]
The reported issue on this ticket is done, so I'm going to close it.  if you want to change this other package, either do it please or open a new ticket so discussion can carry on. :)
