### ISSUE TITLE
"Given there are users" fails if the user already exists.

### ISSUE THREAD

**Issue by rvodden** [paulgibbs/behat-wordpress-extension#128]
The step which drives "Given there are users" creates a new user without checking to see if that user already exists. This prevents, for example, a list of users being provided in the background to a feature.

## Expected behavior
The step `Given there are users' should ensure that users exist.

## Current behavior
If the described user already exists, the step fails.

## Possible solution
Check to see if the user exists prior to creating the user. Possibly update the user data to match that specified in the step.

## Steps to reproduce (for bugs)
Execute the following feature (background runs before each scenario):
```
Feature: Display login names
	In order that users know what they're doing
	As a website user
	I need to be able to see my name on the screen
Background:
    Given there are users:
    | user_login | user_pass |  user_email        | role          |
    | test      | test     |  test@example.com | administrator |

Scenario: The user name should be displayed
Given I am logged in as a test
When I go to the dashboard
Then the username should be test

Scenario: The same scenario, although any one would do
Given I am logged in as a test
When I go to the dashboard
Then the username should be test
```

## Context
This means that user setup can't be done as part of the background to a feature, which is quite a neat place to do it IMHO. 

## Your environment

* Version used: dev-master, but with my fix for #126 included.
* Environment name and version (e.g. PHP 7.1 on nginx 1.11.9): php 7.0.22, apache 2.4
* Server operating system type and version: MacOS Sierra

**Comment by paulgibbs** [comment]
Hi @rvodden - thank you for the great report. I've given this a couple hours' thought.

I agree about Backgrounds being very handy. My initial thought is that, yes, we could add a check to createUser() that checks if the username (etc) already exists prior to creating the user to prevent a failure.

However, it'll slow down the WPCLI driver (which isn't mega-quick because it has to make external requests, but still). This isn't a blocker.

Also, and this is not? documented on the current version of the website because it's newish, but there is a setting that causes WordHat to create a database back-up via a `BeforeScenario` hook, and restore it via `AfterScenario`. If this is news to you, take a look at the markdown directly: https://github.com/paulgibbs/behat-wordpress-extension/blob/42c3afac1f9b40e220f92cd175f3575101678d6d/docs/recipes/faq.md#content

We could have a similar problem to creating users in other areas (e.g. a set of blog posts), and then we'd have to try our best to handle "duplicate" content (is it intentional? not intentional?) in multiple places. This sounds pretty bad.

I think the root of this issue is that content generated by a previous test is interfering with the operation of a subsequent test -- the type of that content is a bit irrelevant. I think ensuring a clean test state is the correct fix for the reported issue.

I'm going to leave this open for a week or two. You might have further feedback that makes me rethink, or someone else comes along with a killer point.

Thanks again @rvodden, and thanks for trying out Wordhat. :)

**Comment by rvodden** [comment]
I really like what you've done here :) 👍 I'm developing a wordpress plugin right now and this extension is definitely making it easier. 

Well the primary key for a post is its ID; and there are no other unique fields. Its perfectly acceptable to have two independent posts with the same title, author and content. Therefore a `Background:` or anything else for that matter, which specified `Given a post ...` could simply create it knowing there would be no issues.

For users, however, the ID, the login and the email *must* be unique. You can't have two users with different IDs but the same login, or the same email. Therefore the `Given a user` clause has to be a touch more intelligent.

Looking down the list of currently supported entities, `user` seems to be the only one for which this argument stands. `Posts` and `Pages` can all be duplicated completely (obviously barring the ID).

I'm with you that tests should be isolated - I think there's a philosophical discussion as to whether a scenario or a feature constitutes a test - and in the interests of flexibility make it a configuration option. As you pointed out, it slows down the WPCLI driver quite a bit, so making it a configuration option helps there too.

I've got a pull request in progress here: 
https://github.com/rvodden/behat-wordpress-extension/tree/issue-128
just got the logic in place ATM; haven't started on the configuration idea.

**Comment by paulgibbs** [comment]
> For users, however, the ID, the login and the email must be unique.

That is a good point.

**Comment by paulgibbs** [comment]
> there's a philosophical discussion as to whether a scenario or a feature constitutes a test 

Right now we went with scenario for granularity -- I think; @stephenharris, do you recall if we had a stronger reason? --, though an argument could be made to have it change to feature. I'm disinclined to have this as a user toggle, I'd rather the project be opinionated about something that small (unless of course hordes of Behat users chase me down in the streets).

**Comment by paulgibbs** [comment]
I wonder, if the current `database.restore_after_test` couldn't default to enabled, which in theory would prevent this class of problem occurring. Maybe. That feature still needs more testing. But hopeful. I think I might create a branch with it on, and let Travis-CI see if it can handle it.

**Comment by rvodden** [comment]
I think there are two ways of achieving test isolation. The first is as you describe - restoring the application to a known state before running the tests. An alternative approach, but ultimately a more flexible one, is mandating that the tests clear up after themselves (i.e. if you create a user, you must delete it afterwards; if you alter an article you must put it back). This second approach is a good deal more work for the author, but does permit running tests in non-dedicated environments. I usually use a prefix (e.g. __test__) to ensure that there are no collisions with 'live' data.

On reflection I agree that a configuration option isn't the answer. However database.restore_after_test is a side effect, and I think it would be dangerous to not ask a use to enable it explicitly. Another option is to expose it in step which could be included in the background (i.e. run before every scenario). These aren't the right words, but something along the lines of ```Given wordpress is restored to a known good point```. 

I would be completely sold on this idea if Behat 3 supported chained steps. This would give the BDD author the choice to expose that step in the feature (ugly IMHO) or as a 'sub-step' in some other background steps. Alas not only is step chaining not supported, but it looks like the Behat team have decided against implementing it, albeit for good reason. 

 On other news, I've come up with some logic - see the latest commit in the (not yet) PR above - which doesn't slow down the CLI driver. Helpfully both the wpphp and wpcli drivers throw exceptions if you try and create a user which already exists. This means that rather than searching for the user (which was both of our initial approaches), we can attempt to create the user and catch the exception if it occurs. This means there is no measurable depreciation in performance for either driver.

**Comment by stephenharris** [comment]
@paulgibbs We reset between scenarios because a scenario could alter the DB and impact other scenarios. This is kind of what's happening here as the Background runs as part of each scenario.

Resetting the DB is the most robust way to go forward here. We have no idea how updating an e existng user might impact third-party code and thus potentially muddy the tests.

I think we support having a 'reset database' tag. Do features support tags? That could be a convenient way of telling Behat to trigger the DB after every scenario in a feature.

Resetinf the DB will slow down the tests - which is the disadvantage of system testing - but then system testing should have minimal tests: focussing on high level behaviour and business critical functionality. Unit and integration tests should cover the rest.

**Comment by paulgibbs** [comment]
> Do features support tags?

Yes

**Comment by rvodden** [comment]
I think a reset database tag is a really neat way of fixing this one :) 👍

**Comment by paulgibbs** [comment]
If the backup option is enabled, it requires a scenario or feature to be tagged "@db". This is how it works. Some tests won't touch the DB and obviously restoring the DB in that situation is a waste of time 

--- 
Paul Gibbs

**Comment by rvodden** [comment]
So I've been pondering this. I think we all agree on a couple of things:
1) Tests should be self contained, i.e. only modify data they create, and possibly clear it up afterwards
2) DB restoration could be slow.
So an approach an author may choose to take is to create all the seed data in advance (outside of WordHat or Behat) and let the suite run without restoration. At present if we have a `Given a there are users:` line, and that user already exists then WordHat fails. So I think a helpful middle ground would be to verify the user metadata matches what is found, and only fail if it does not. I.e.:

* if the user specified doesn't exist, created it with the specified metadata and succeed
* if the user exists, see if the metadata matches the pre-created user and succeed if it does; throw an error if it does not.

How does that sound? Its pretty straightforward to code, so if we agree I can get you a pull request by the weekend.

**Comment by paulgibbs** [comment]
Let's let @stephenharris have the decision here.

**Comment by stephenharris** [comment]
Sorry slow to respond here. I think that sounds like a reasonable approach.

I think any error messages would need to make it clear. the user exists but with different data (and preferably specify where they differ) - Just to aid debugging.

**Comment by rvodden** [comment]
Cool. I'll spin up a PR. I completely agree with you about the clarity of the error messages!

**Comment by paulgibbs** [comment]
If the user creation change, as described in this discussion, can be patched before the end of October, we will include it in 1.0, else we'll bump it to the future release milestone.
