### ISSUE TITLE
Don't access `$this->getDriver()->x` in context classes

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/behat-wordpress-extension#134]
In our Behat context classes (the ones that derive from RawWordpressContext), we interact with the website programmatically via the drivers system. Rather than use the result of the `getDriver()`directly, these touches should be abstracted via a method in RawWordpressContext.

## Current behaviour
An example of what I want to change is EditPostContext, in `iGoToEditScreenForPostType()`:
`$post = $this->getDriver()->content->get($title, ['by' => 'title', 'post_type' => $post_type]);`

## Possible solution
This should be changed to something like:
`$post = $this->getContent($title, ['by' => 'title', 'post_type' => $post_type]);` and that new method implemented.

You will see that methods such as `createContent()` and `deleteContent()` already exist. This is what we want and is a good model. For history's sake, these methods were left over from the first version of the Drivers API, and until recently they did have a note commenting that they'd be removed in 1.0, but I've obviously changed my mind.

Note that if a Driver Element doesn't have a method implemented (e.g. most don't have `update()` implemented yet), then we don't need to create these top-level wrapper methods for now.

## Context
This will help future-proof against changes to the Driver Elements API, and arguably simplifies the main API.

**Comment by paulgibbs** [comment]
@rvodden I don't want to scare you off :) but I think you commented somewhere that if there was anything else you could help out with, you might be interested. :)

Any interested on this?

**Comment by rvodden** [comment]
Yeah - I can have a look at that. 

It feels like - because as you say these methods form part of the Driver API - they should be raised up to the DriverInterface and then declared as abstract in the BaseDriver? 

This measn that the API will be entirely declared and documented in the DriverInterface. It will have the side effect that BlackBoxDriver will have a lot of implementations that do nothing except throw an UnsupportedDriverActionException; but I think that's neater than just an empty class?

**Comment by paulgibbs** [comment]
Moving them into the `DriverInterface` is one good idea, the other I proposed is moving them into `RawWordpressContext`. I haven't thought about what's best, architecturally.

If anyone else has comments or a strong opinion, those'd be great.

And don't worry about BlackBoxDriver -- we can probably just delete that. It's not documented, and exists only because the Drupal Behat Extension had implemented it (see https://behat-drupal-extension.readthedocs.io/en/3.1/blackbox.html), the idea being there's no driver communication at all and everything is done in the web browser. But ain't nobody got time to implement all driver stuff in a context using Mink commands, and i'm probably happy just to insist people use the WPPHP or the WPCLI driver for the forseeable.

**Comment by rvodden** [comment]
I've been fiddling with this a bit, and we're in danger of turning `RawWordpressContext` into a pretty hectic class. To combat this I'm going to create a set of Traits which implement the Element specific code (`ContentAwareContextTrait`, `DatabaseAwareContextTrait` etc...). These can then be pulled into the Contexts on demand. 

The only alternative I can see is to create base Elements (e.g. `BaseContentElement`) which is probably better from a purist perspective (the Content logic stays with the `ContentElement`) but  creates real headaches when it comes to Context instantiation. I'll write it up properly as it might be something we want to do in a future release; but its way beyond the scope of this feature. 

Shout if you object to the trait idea, or if you can think of a better naming convention, or for any other reason really.

**Comment by paulgibbs** [comment]
Traits seems a really good idea!

--- 
Paul Gibbs

**Comment by rvodden** [comment]
I'm posting a keepalive :-) I'm working on this and you can see progress here:

https://github.com/rvodden/behat-wordpress-extension/commits/fix-134

should have PR ready over the weekend. I'll explain some of my thinking in the morning.

**Comment by rvodden** [comment]
Right - I'm a few comments away from submitting a pull request- although I fully expect there to be more work to do after you take a look. I was given two aims:

1) Remove `$this->getdriver()` from the Context classes,
1) Simplify the driver API.

In order to achieve that I've effectively established a few architectural principles, some of which are more implemented than others. I'm happy to take these to completion as part of this PR should you agree they're the right way to go. I've tried to keep as close to SOLID and DRY principles as I can without getting all daft and academic about it.

1) Contexts only map from steps to code. 
1) Drivers only contain CRUD operations and things which are driver specific
1) Any 'friendly' helper functions should live in the newly created entity traits and should be driver agnostic.

This means that the RawWordpressContext can be lighter than it was, the 'friendly' logic having been refactored into the various entity traits which now exist. 

I've got to the point where I've eradicated `$this->getdriver()`. It seems sensible that I crack on and take this refactor to its logical confusion. Assuming you're happy :-)
