### ISSUE TITLE
How to pass on meta_input to ContentElement->create()

### ISSUE THREAD

**Issue by alfhen** [paulgibbs/behat-wordpress-extension#157]
I am using the build in  ```function iAmViewingBlogPost($post_data_or_title)``` 
And my feature looks like

``` gherkin
@db
Feature: Viewing page meta description

    Scenario: Viewing a single article with a teaser description
        Given I am viewing a post:
           | post_type            | post_title      | post_content    | post_status | meta_input_teaser_description |
           | contenthub_composite | My about page   | About this site | publish     | test description |
        Then I should see the meta "og:description" equal "test description"

```

I can see by inspecting ```PaulGibbs\WordpressBehatExtension\Driver\Element\Wpcli\ContentElement::create()``` 
that the code supports passing on meta_input just like the ```wp_insert_post()``` method.

But my question is how to pass on meta_input to the function using the table syntax in the feature shown above. For instance if I would like to set a post_meta with the key ```teaser_description``` then how do I go about that?

**Comment by paulgibbs** [comment]
Hi @alfhen, thanks for trying out WordHat!

You have a good question. You're right that the `meta_input` and `tax_input` arguments are "supported" because the WP-CLI driver supports them, and we needed WordHat to keep things consistent between our different drivers.

What I didn't realise until I went to use `tax_input` recently was that WP-CLI itself, despite it also whitelisting the argument, doesn't support `tax_input` or `meta_input` due to no decision being made about how to structure an array on the command line. (Like, how exactly? JSON? Serialized PHP object? I don't know.)

So, similarly, these two arguments are not supported in WordHat at the moment in a `TableNode`.

On this other hack project I mentioned, https://github.com/humanmade/retreat-2017-automated-testing/blob/master/features/bootstrap/FeatureContext.php#L103 I had to implement my own "create custom post type" step definition to support this (but mainly so I could use the step definition phrasing that was most appropriate for my hack project) and pass the data to the `content->create` driver directly. That's probably your best bet for the time being.

**Comment by alfhen** [comment]
Thanks for the swift reply! And thank you for all the hard work on Wordhat!
I ended up adding 
``` php
/**
     * @Given I am viewing a custom post:
     *
     * @param \Behat\Gherkin\Node\TableNode $customPosts
     */
    public function iAmViewingACustomPost(TableNode $customPosts)
    {
        $createPostArgs = collect($customPosts->getHash())->first();

        collect($createPostArgs)->filter(function($value, $key) {
            return strpos($key, 'meta:') === 0;
        })->each(function($value, $acfField) use(&$createPostArgs) {
            $acfFieldName = explode(':', $acfField)[1];
            $createPostArgs['meta_input'][$acfFieldName] = $value;
        });

        $post = $this->createContent($createPostArgs);

        $this->visitPath($post['url']);
    }
```
To my FeatureContext, and it works. My feature now looks like 
``` gherkin
@db
Feature: Viewing page meta description

    Scenario: Viewing a single article with a teaser description and no teaser description
        Given I am viewing a custom post:
           | post_type            | post_title     | post_status | meta:teaser_description |
           | contenthub_composite | My about page  | publish     | test description |
        Then I should see the meta "description" equal "test description"

    Scenario: Viewing a single article with a description and no teaser description
        Given I am viewing a custom post:
          | post_type            | post_title      | post_status | meta:description |
          | contenthub_composite | My about page   | publish     | test description |
        Then I should see the meta "description" equal "test description"

```
The problem is that since I am using ACF flexible content fields, I find it hard how to figure out a way to describe the flexible fields in the gherkin table syntax.. So I am not sure that this might be the right setup for my use case. Have you any experience using to set complexed ACF flexible content fields.

**Comment by paulgibbs** [comment]
Yeah, not a bad approach! Just not sure it scales horizontally very well (literally the line length!). And entering serialised data or raw arrays in this format for meta is going to get messy.

--

What are you trying to test here? Does "I should see the meta X equal Y" refer to post meta, or the `<meta>` tag in the HTML?

**Comment by alfhen** [comment]
Yeah it would not scale very well, and it would end in very long lines.
No It refers to the meta tag in the HTML:

``` php 

/**
     * @Then I should see the meta :arg1 equal :arg2
     *
     * @param $metaName
     * @param $metaValue
     *
     * @return boolean
     */
    public function iShouldSeeTheMetaEqual($metaName, $metaValue)
    {
        $html = $this->getSession()->getPage()->getHtml();
        return collect($this->getMetaTags($html))->get($metaName) === $metaValue;
    }
```
It might be more descriptive, if It was I should see the meta_tag x equal y. 
Anyway thanks for your help. I think I will have to take another approach. 
Since the data model of my custom post type is quite complex, and would be hard to replicate in the TableNode format.

**Comment by paulgibbs** [comment]
OK. I'd think about instead of using a tablenode to set up a post, just do that all in your iAmViewingACustomPost(). Remember, you can do something like this:

```
/**
 * @Given I am viewing a magical post
 * @Given I am viewing a magical post that doesn't not have :field_name set
 */
function something( $field_name = '' ) {
 // argument is optional, use it to delete some specific post meta after creation (or whatever).
}
```

Your special posts should have all the correct properties set for your user story requirement, and you want to test for the absence of some of them. Not all of them: https://watirmelon.blog/2012/01/31/introducing-the-software-testing-ice-cream-cone/ is an interesting read
