### ISSUE TITLE
Document usage examples

### ISSUE THREAD

**Issue by mitramejia** [paulgibbs/behat-wordpress-extension#9]
The docs cover configuration, but no usage examples, it would be great. Even though I've configured the extension I'm not sure how I am supposed to use it.

**Comment by dan-westall** [comment]
@mitramejia Heres a example of a quick feature i wrote for quick draft widget.

`Feature: Test quick draft
test

  @javascript
  Scenario:
    Given I am logged in as an admin
    When I go to wp-admin
    When I fill in "post_title" with "Behavior Driven Development"
    And I press "save"
    Then I should see "Behavior Driven Development" in the "#dashboard_quick_press li:nth-child(1) .draft-title a" element`

That should give you an idea, for more commands `vendor/bin/behat -dl` and of course the behat docs.

**Comment by paulgibbs** [comment]
Hi @mitramejia 

Thanks for the feedback. I agree. It's early days, and we'll get it done sooner rather than later.
One thing I haven't decided on is the balance between telling people "go read http://docs.behat.org/en/latest/quick_start.html" vs going into detail in the WordHat docs. As this project is for developers, I'm thinking to balance the documentation further to that.

I think I'll start by adding a "what's next?" step to the documentation, and see how it all feels then.

**Comment by mitramejia** [comment]
thanks @dan-westall 👍  

@paulgibbs that would be great.

**Comment by paulgibbs** [comment]
I overhauled the installation page on the website and added a 'intro to Behat' page. I still would like a 'next steps' but docs take me x10 longer to write than code, so will revisit that after 1.0.

**Comment by paulgibbs** [comment]
I did it anyway. I've just written more "getting started" docs (not live yet on the website), I think things will be better when it goes live soon.
